#!/usr/bin/env python

"""
WSGI server, standalone if ran from the shell but can also be used for WSGI
bootstrap script.
"""

from vimpaste.app import app as application

if __name__ == '__main__':
    from wsgiref.simple_server import make_server

    httpd = make_server('localhost', 9000, application)
    print("Serving vimpaste for debug on http://localhost:9000/.")
    httpd.serve_forever()
